clear
echo Removing database file...
rm test.db
echo Creating database file...
python3 create_database_orm.py test
echo Inserting test data...
python3 load_data_orm.py dane/test.csv test
echo Inserting test data \(again!\)...
python3 load_data_orm.py dane/test.csv test
echo Retrieving data from database...
if [ $# = 1 ]; then
	python3 get_data_orm.py test | less
else
	python3 get_data_orm.py test
fi
